<img src="/header2.png" class="img-fluid">
<div class="container">
    <div class="row">
        <?php $this->view('alerts/_success'); ?>
        <?php $this->view('alerts/_error'); ?>
    </div>
    
    <div class="row h-100 justify-content-center align-items-center mb-4">
        
        <h1>Loren</h1>
        <p class="text-justify">
            Loren é um microframework MVC construído inicialmente para princípios de estudo em PHP, porém, é um framework funcional que contém funcionalidades, como
            criação de rotas, controllers, models e views. Nele existe o suporte pra dois 3 tipos de banco de dados, que seria o MySQL, PostgreSQL e o SQLite. As 
            configurações do banco de dados podem ser feitas dentro do framework, é só seguir as instruções na documentação :D.<br>
            O intuito do framework não é tornar um framework comercial no início, é apenas um framework para estudos sujeito a modificações conforme o nível de 
            conhecimento do autor for aumentando haha. O Loren é um framework totalmente open-source aceitando contribuições, basta entrar no github do projeto
            <a href="https://github.com/thdrps/loren" target="_blank">clicando aqui</a>.<br>
            O nome Loren foi escolhido pensando em umas das inspirações do autor no passado, e também, porque é um nome bonito xD.<br>
            Foi escolhido como logo o símbolo do Brasil apenas para mostrar o orgulho e pátria, e local de nascimento do autor.<br>
            Caso queira contatar o autor, é só segui-lo nas redes sociais que está no rodapé.<br>
            Espero que curta o desenvolvimento a partir de desse framework e que sempre esteja indicando erros e melhorias para que o Loren sempre possa continuar a evoluir.<br><br>

                <i>"Love will tear us apart."</i><br>

        </p>
        <div>
            <a href="https://github.com/thdrps/loren" class="btn btn-success"><i class="fas fa-arrow-circle-right"></i> Getting started</a>
            <a href="#" class="btn btn-success"><i class="fas fa-book"></i> Read the docs</a>
        </div>
    </div>
    <footer>
        <div class="row h-100 justify-content-center align-items-center">
            <p>Copyright &copy; 2018. Todos os direitos reservados.</p>
        </div>
        <div class="row h-100 justify-content-center align-items-center mb-5">
        <a href="https://twitter.com/thdrps" class="btn btn-success ml-3" target="_blank"><i class="fab fa-twitter" ></i></a>
        <a href="https://www.facebook.com/leonardo.pinheiro.9235199" class="btn btn-success ml-2" target="_blank"><i class="fab fa-facebook-f"></i></a>
        <a href="https://www.instagram.com/thdrps/?hl=pt-br" class="btn btn-success ml-2" target="_blank"><i class="fab fa-instagram"></i></a>
        </div>
    </footer>
</div>
