<?php if(isset($this->success) && $this->success): ?>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <?php foreach($this->success as $msg): ?>
            <p><?= $msg ?></p>
        <?php endforeach; ?>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<?php endif; ?>