<div class="container h-100 vertical-center">
    <div class="row h-100 justify-content-center align-items-center">
        <div class="col-xs-12 col-xs-offset-0 col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title text-center"><?php echo $this->getPageTitle() ?> <i class="fas fa-user-plus"></i></h3>
                </div>
                <div class="panel-body">

                    <form action="/user/store" method="post" accept-charset="utf-8">

                        <div class="form-group <?php echo ($this->errors['name']) ? 'has-error' : '' ?>">
                            <label for="name" class="control-label">Name</label>
                            <input type="text" name="name" placeholder="Loren" class="form-control"
                                   value="<?php echo (isset($this->inputs['name'])) ? $this->inputs['name'] : '' ?>">
                            <?php if (isset($this->errors['name'])): ?>
                                <span class="help-block"><?php echo $this->errors['name'] ?></span>
                            <?php endif; ?>
                        </div>

                        <div class="form-group <?php echo ($this->errors['email']) ? 'has-error' : '' ?>">
                            <label for="email" class="control-label">E-mail</label>
                            <input type="text" name="email" placeholder="loren@brazil.com" class="form-control"
                                   value="<?php echo (isset($this->inputs['email'])) ? $this->inputs['email'] : '' ?>">
                            <?php if (isset($this->errors['email'])): ?>
                                <span class="help-block"><?php echo $this->errors['email'] ?></span>
                            <?php endif; ?>
                        </div>

                        <div class="form-group <?php echo ($this->errors['password']) ? 'has-error' : '' ?>">
                            <label for="password" class="control-label">Password</label>
                            <input type="password" name="password" placeholder="•••••••••" class="form-control">
                            <?php if (isset($this->errors['password'])): ?>
                                <span class="help-block"><?php echo $this->errors['password'] ?></span>
                            <?php endif; ?>
                        </div>

                        <button type="submit" class="btn btn-success btn-block">
                        <i class="fas fa-user-plus"></i> Save
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>