<div class="container h-100 vertical-center">
    <div class="row h-100 justify-content-center align-items-center">
        <div class="col-xs-12 col-xs-offset-0 col-md-4 col-md-offset-4 ">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title text-center"><?php echo $this->getPageTitle() ?> <i class="fas fa-user-check"></i></h3>
                </div>
                <div class="panel-body">

                    <?php $this->view('alerts/_error'); ?>

                    <form action="/login/auth" method="post" accept-charset="utf-8">

                        <div class="form-group">
                            <label for="email" class="control-label">E-mail</label>
                            <input type="text" name="email" placeholder="loren@brazil.com" class="form-control"
                                   value="<?php echo (isset($this->inputs['email'])) ? $this->inputs['email'] : '' ?>">
                        </div>

                        <div class="form-group">
                            <label for="password" class="control-label">Password</label>
                            <input type="password" name="password" placeholder="•••••••••" class="form-control">
                        </div>

                        <button type="submit" class="btn btn-success btn-block">
                        <i class="fas fa-user-check"></i> Login
                        </button>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>