<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="/favicon.gif">

    <!-- CSS -->
    <link rel="stylesheet" href="/assets/css/style.css">

    <title>Loren Framework</title>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/"><img src="/favicon.gif" class="pull-left"> Loren Framework</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/about">About</a>
            </li>
        </ul>
    </div>
   </nav>
  <div class="container h-100 vertical-center" style="margin-top: 5%;">
        <div class="row h-100 justify-content-center align-items-center">
            <img src="/404.gif">
        </div>
        <div class="row h-100 justify-content-center align-items-">
            <div class="text-center">
                <h1>404</h1>
                <h2>Page not found</h2>
                <p>Please, check if the URL is correct.</p>
            </div>    
        </div>
        
    </div>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="/assets/js/jquery-3.3.1.min.js"></script>
    <script src="/assets/js/popper.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
  </body>
</html>