<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/"><img src="/favicon.gif" class="pull-left ml-5"> Loren Micro Framework</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/"><i class="fas fa-home"></i> Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://github.com/thdrps/loren" target="_blank"><i class="fab fa-github"></i> Source Code</a>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <?php if($this->auth::isLogged()) : ?>
            <li class="dropdown float-right">
            <button class="btn btn-outline-success dropdown-toggle mr-5" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user"></i> <?= $this->auth->name() ?>
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="/logout"><i class="fas fa-sign-out-alt"></i> Sign out</a>
                <!-- <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a> -->
            </div>
            </li>
        <?php else : ?>
            <li><a href="/login" class="btn btn-outline-success mr-3"><i class="fas fa-user-check"></i> Sign-in</a></li>
            <li><a href="/user/create" class="btn btn-success mr-5"><i class="fas fa-user-plus"></i> Register</a></li>
        <?php endif; ?>
    </ul>
    <form class="form-inline my-2 my-lg-0">
    </form>
  </div>
</nav>